### PR TITLE
I'm the server son, so I deserve it.

### PR DESCRIPTION
**Pull request by thetayloredman**
Yes.

### CODE REVIEW

**Comment by AlphaSerpentis** [comment]
Reject it, only the mother can use it

**Comment by thetayloredman** [comment]
🚫

**Comment by thetayloredman** [comment]
no reject

**Comment by thetayloredman** [comment]
@DeveloperDrago merge wen

**Comment by thetayloredman** [comment]
**DeveloperDrago** commented now
now

**Comment by DeveloperDrago** [comment]
Server Mommy Rejects therefore n o ( You add your own sort of command that you can use only instead tho )

**Comment by thetayloredman** [comment]
aight
don't close, i'll adjust this one

**Comment by DeveloperDrago** [comment]
Oh dang I didn't know this would comment realitime

**Comment by thetayloredman** [comment]
it sends HTTP requests every once and a while to check

**Comment by thetayloredman** [comment]
@DeveloperDrago what about 

```js
message.reply(eval(args.join(' ')))
```

sound ok?

**Comment by thetayloredman** [comment]
lmao jk

**Comment by thetayloredman** [comment]
@DeveloperDrago there

**Comment by thetayloredman** [comment]
lol

**Pull request merged**
