### PR TITLE
Added basic economy features

### PR DESCRIPTION
**Pull request by LostNuke**
Changed the GuildMember structure, so you can do member.pay or member.add member.addBank to interact with the Currency.

Change the Guild Structure so you can get the total amount of the money in the Guild for future use.

Added a new property to the settings.json so you can change the name

Added all the different commands like bank/pay/add/remove

### CODE REVIEW

**Comment by thetayloredman** [comment]
"Soo... You're officially a Furry now?" ~ Lost but now BBHC

**Comment by LostNuke** [comment]
You wanna be licked?

**Comment by thetayloredman** [comment]
yes pls~

**Comment by DeveloperVulpo** [comment]
I-

**Comment by LostNuke** [comment]
Look Jason wants a lick too

**Comment by LostNuke** [comment]
Imagine using Discord for chatting. Why Discord when you have GitHub pull requests?

**Review by DeveloperVulpo — APPROVED** [review]

**Comment by DeveloperVulpo** [comment]
Indeed

**Review by thetayloredman — COMMENTED** [review]
nom

**Comment by dev-sda1** [comment]
what the hell did I just read?

**Comment by thetayloredman** [comment]
> what the hell did I just read?

Uhhhhh- furries doing their thing ig

**Comment by dev-sda1** [comment]
yeah I guess youwu could say sowo

**Comment by thetayloredman** [comment]
> yeah I guess youwu could say sowo

*sigh* OwO What's this?

**Comment by LostNuke** [comment]
I...

**Comment by dev-sda1** [comment]
> OwO What's this?

a puwull request clearly :3c

**Comment by thetayloredman** [comment]
> > OwO What's this?
> 
> a puwull request clearly :3c

wait i thOwOught it was an issUwUe?

**Comment by dev-sda1** [comment]
>wait i thOwOught it was an issUwUe?

An issuwue which ended with a puwull request

**Comment by thetayloredman** [comment]
which issUwUe?

**Comment by dev-sda1** [comment]
> which issUwUe?

This issuwue: #42 OwO

**Comment by thetayloredman** [comment]
That's a pUwUll reqUwUest, not an issUwUe...

**Comment by dev-sda1** [comment]
ah shuwut gowot them mixed uwup

**Comment by thetayloredman** [comment]
Wtf has this tUwUrned intOwO

**Comment by thetayloredman** [comment]
Is fine *pats*

**Comment by dev-sda1** [comment]
> Wtf has this tUwUrned intOwO

 gowod knowos lol

**Comment by thetayloredman** [comment]
@dev-sda1 is emitting all the trUwUe fax right here

**Comment by dev-sda1** [comment]
o///o

**Comment by LostNuke** [comment]
Fuck Discord, all my homies use Gitcord

**Comment by dev-sda1** [comment]
gitcord >>> discord

**Comment by thetayloredman** [comment]
> gitcord >>> discord

trUwUe

**Comment by dev-sda1** [comment]
owo

**Pull request merged**
