### PR TITLE
Install Instructions for Beginners

### PR DESCRIPTION
**Pull request by EchoLynx**
Getting the FurDevs bot running took me a bit of effort because I had to remember stuff I hadn't done in a while. Since capturing that experience can be useful both as a learning experience and for future-potential-contributors, I decided to write up a more detailed set of installation instructions. Here they are!

If you don't like 'em or want 'em, that's fine - they were fun to write.

### CODE REVIEW

**Review by DeveloperDrago — APPROVED** [review]
Looks amazing

**Comment by DeveloperDrago** [comment]
Thanks @EchoLynx <3

**Comment by thetayloredman** [comment]
#35: This PR needs to be modified before it's suitable for merge.

**Comment by DeveloperDrago** [comment]
What are the modifications needed @thetayloredman 🤔

**Comment by thetayloredman** [comment]
@EchoLynx Please run the following commands:

```bash
git commit --allow-empty -m "Reset"
git push
```

Then, remake the pull request.

**Comment by EchoLynx** [comment]
> @EchoLynx Please run the following commands:
> 
> ```shell
> git commit --allow-empty -m "Reset"
> git push
> ```
> 
> Then, remake the pull request.

I'm confused... Do you still need me to do this now that you've made PR #36?

**Pull request merged**
