### PR TITLE
refactor a lot of the repo

### PR DESCRIPTION
**Pull request by thetayloredman**
This PR is WIP, but please give reviews!

### CODE REVIEW

**Comment by DeveloperVulpo** [comment]
Whoops I pressed the wrong button lmao

**Comment by thetayloredman** [comment]
> Whoops I pressed the wrong button lmao

Lol, I made it draft so you ***WOULDNT*** merge it by accident.

**Comment by DeveloperVulpo** [comment]
Whoops my finger slipped and merged it

**Comment by thetayloredman** [comment]
Die /s

**Review by DeveloperVulpo — APPROVED** [review]

**Comment by thetayloredman** [comment]
Resolving conflicts...

**Comment by thetayloredman** [comment]
**Before merging:** REVIEW THIS PR AGAIN! I may have messed up resolving conflicts.

**Comment by DeveloperVulpo** [comment]
No

**Pull request closed without merging**
